# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  # machine specs live in hw/gpd_pocket_2.nix

  boot.supportedFilesystems = ["zfs"];

  fileSystems."/" =
    { device = config.gensokyo.disks.root or "/dev/disk/by-label/dusk-root";
      fsType = "ext4";
    };

  #boot.initrd.luks.devices."form0".device = "/dev/mmcblk0";

  #fileSystems."/boot" =
  #  { device = "/dev/disk/by-uuid/REDACTED";
  #    fsType = "ext4";
  #  };

  fileSystems."/boot" =
    { device = config.gensokyo.disks.boot or "/dev/disk/by-label/DUSK_BOOT";
      fsType = "vfat";
    };

  #networking.hostId = "AAAAAAAA";
  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u3u3.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Use the systemd-boot EFI boot loader.
  # boot.loader.systemd-boot.enable = lib.mkForce false;
  # boot.loader.systemd-boot.enable = true;
  # boot.loader.efi.canTouchEfiVariables = true;
  # boot.loader.efi.efiSysMountPoint = "/boot/EFI";
  # boot.loader.grub.efiSupport = true;
  # boot.loader.grub.efiInstallAsRemovable = true;
  # boot.loader.grub.device = "nodev";

  #boot.loader.grub.gfxpayloadEfi = "keep";
  #boot.loader.grub.gfxmodeEfi = "1200x1920";

  boot.lanzaboote = {
    enable = true;
    pkiBundle = "/var/secret/secureboot";
  };

  # Lanzaboote currently replaces the systemd-boot module.
  # This setting is usually set to true in configuration.nix
  # generated at installation time. So we force it to false
  # for now.
  boot.loader.systemd-boot.enable = lib.mkForce false;

  # console rotation lives in hw/gpd_pocket_2.nix; boot.shell_on_fail in base

  boot.initrd.secrets = {"/form.h" = /var/secret/crypt/form.h;};

  boot.initrd.luks.devices = {
    crypted = {
      device = config.gensokyo.disks.crypted or "/dev/disk/by-label/dusk-crypted";
      header = "/form.h";
      preLVM = true;
    };
  };
}
