# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  hardware.opengl.enable = true;
  #hardware.opengl.driSupport = true;
  #hardware.opengl.driSupport32Bit = true;
  #hardware.opengl.setLdLibraryPath = true;
  # hardware.cpu.intel.updateMicrocode = true;
  boot.kernelModules = [ "kvm-intel" ];
  #services.xserver.videoDrivers = ["intel"];
  console.font = "latarcyrheb-sun32";

  # hardware.enableAllFirmware = true;
  hardware.enableRedistributableFirmware = true;
  hardware.firmware = [ pkgs.wireless-regdb ]; # is this necessary?

  #powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  services.xserver.videoDrivers = ["i915"];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usb_storage" "usbhid" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = ["zfs"];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/REDACTED";
      fsType = "ext4";
    };

  #boot.initrd.luks.devices."form0".device = "/dev/mmcblk0";

  #fileSystems."/boot" =
  #  { device = "/dev/disk/by-uuid/REDACTED";
  #    fsType = "ext4";
  #  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/REDACTED";
      fsType = "vfat";
    };

  networking.hostId = "AAAAAAAA";
  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u3u3.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Use the systemd-boot EFI boot loader.
  # boot.loader.systemd-boot.enable = lib.mkForce false;
  # boot.loader.systemd-boot.enable = true;
  # boot.loader.efi.canTouchEfiVariables = true;
  # boot.loader.efi.efiSysMountPoint = "/boot/EFI";
  # boot.loader.grub.efiSupport = true;
  # boot.loader.grub.efiInstallAsRemovable = true;
  # boot.loader.grub.device = "nodev";

  #boot.loader.grub.gfxpayloadEfi = "keep";
  #boot.loader.grub.gfxmodeEfi = "1200x1920";

  boot.lanzaboote = {
    enable = true;
    pkiBundle = "/var/secret/secureboot";
  };

  # Lanzaboote currently replaces the systemd-boot module.
  # This setting is usually set to true in configuration.nix
  # generated at installation time. So we force it to false
  # for now.
  boot.loader.systemd-boot.enable = lib.mkForce false;

  boot.kernelParams = ["boot.shell_on_fail" "video=efifb" "fbcon=rotate:1"];

  boot.initrd.secrets = {"/form.h" = /var/secret/crypt/form.h;};

  boot.initrd.luks.devices = {
    crypted = {
      device = "/dev/disk/by-id/REDACTED";
      header = "/form.h";
      preLVM = true;
    };
  };
}