# VST/CompCert template project.
#
# Everything is built into build/ :
#   build/fib.v build/main.v     clightgen output (the Clight ASTs)
#   build/*.o build/fib          ccomp output (the actual program)
#   build/*.vo build/*.glob      Coq proof artifacts
#
# Run this inside `nix develop`, which puts coqc/clightgen/ccomp on PATH and
# VST+CompCert+ITree on COQPATH.

SRC      := src
BUILD    := build
TOP      := FibVST

CLIGHTGEN ?= clightgen
COQC      ?= coqc
COQDEP    ?= coqdep
CCOMP     ?= ccomp

# -normalize is mandatory for VST: without it, floyd's forward/ tactics refuse
# expressions containing internal memory dereferences.
CGFLAGS    := -normalize -I $(SRC)
COQFLAGS   := -Q $(BUILD) $(TOP) -w -deprecated-from-Coq
CCOMPFLAGS := -O -I $(SRC)

# Proof sources, in dependency order.
PROOFS := Fib_model IO_model Fib_spec Whole_prog Main_spec Verif_fib Verif_main Link
# Clight ASTs generated by clightgen.
ASTS   := fib main

AST_V   := $(addprefix $(BUILD)/,$(addsuffix .v,$(ASTS)))
VOFILES := $(addprefix $(BUILD)/,$(addsuffix .vo,$(ASTS) $(PROOFS)))
OFILES  := $(addprefix $(BUILD)/,$(addsuffix .o,$(ASTS)))

.PHONY: all bin proofs audit smoke clean depend
.DELETE_ON_ERROR:

all: bin proofs

bin: $(BUILD)/fib

proofs: $(VOFILES)

$(BUILD):
	mkdir -p $(BUILD)

# --- C -----------------------------------------------------------------
#
# The proofs are about CompCert's semantics of these translation units, so the
# binary is built with ccomp (the verified compiler), not with gcc.

$(BUILD)/%.o: $(SRC)/%.c $(SRC)/fib.h | $(BUILD)
	$(CCOMP) $(CCOMPFLAGS) -c $< -o $@

$(BUILD)/fib: $(OFILES)
	$(CCOMP) $(CCOMPFLAGS) -o $@ $(OFILES)

# --- clightgen ---------------------------------------------------------
#
# Both translation units go through a single clightgen invocation: `-o` is
# rejected for multiple inputs, and one invocation guarantees the two units
# share builtin tables and composite environments, which linking requires.
# clightgen writes each .v beside its .c, so move them into build/ after.

$(AST_V) &: $(SRC)/fib.c $(SRC)/main.c $(SRC)/fib.h | $(BUILD)
	$(CLIGHTGEN) $(CGFLAGS) $(SRC)/fib.c $(SRC)/main.c
	mv $(SRC)/fib.v $(SRC)/main.v $(BUILD)/

# --- Coq ---------------------------------------------------------------
#
# coqc derives a file's logical name from its -o path against the load path,
# so `-Q build FibVST -o build/X.vo src/X.v` compiles src/X.v as FibVST.X.

$(BUILD)/%.vo: $(SRC)/%.v | $(BUILD)
	$(COQC) $(COQFLAGS) -o $@ -dump-glob $(@:.vo=.glob) $<

$(BUILD)/%.vo: $(BUILD)/%.v | $(BUILD)
	$(COQC) $(COQFLAGS) -o $@ -dump-glob $(@:.vo=.glob) $<

# Dependencies among the proof files.  coqdep names its targets after the
# source path, so rewrite src/X.vo into build/X.vo.
$(BUILD)/.depend: $(addprefix $(SRC)/,$(addsuffix .v,$(PROOFS))) $(AST_V) | $(BUILD)
	$(COQDEP) -Q $(SRC) $(TOP) $(COQFLAGS) $^ 2>/dev/null \
	  | sed -E 's#$(SRC)/([A-Za-z0-9_]+)\.(vo|glob|vos|vok)#$(BUILD)/\1.\2#g' \
	  > $@

depend: $(BUILD)/.depend

# For editors / IDEs: a _CoqProject reflecting the current devshell paths.
# Not needed by the Makefile, which takes its paths from COQPATH.
.PHONY: _CoqProject
_CoqProject:
	@{ echo "-Q $(BUILD) $(TOP)"; \
	   echo "-arg -w -arg -deprecated-from-Coq"; \
	   echo "$$COQPATH" | tr : '\n' | sed '/^$$/d' | sort -u | while read -r d; do \
	     for l in "$$d"/*; do \
	       [ -d "$$l" ] && echo "-Q $$l $$(basename "$$l")"; \
	     done; \
	   done; } > $@
	@echo "wrote $@"

ifeq (,$(filter clean depend,$(MAKECMDGOALS)))
-include $(BUILD)/.depend
endif

# --- audit -------------------------------------------------------------
#
# The point of the project is that the theorems are proved, not admitted.
# `Print Assumptions` reports an Admitted lemma as an axiom named after
# itself, so if anything in our own FibVST.* namespace appears below, a proof
# is incomplete.  What does appear is the classical-logic axioms VST is built
# on, CompCert's parameters for unspecified external functions, and VST's own
# inline_external_call_mem_events.

AUDIT_THMS := Verif_fib.body_fib Link.prog_correct Link.prog_prints_fib
# Any of our own modules appearing in a Print Assumptions output means one of
# our lemmas was Admitted (Coq lists it as an axiom, under its short name).
AUDIT_NS   := $(shell echo '$(PROOFS)' | tr ' ' '|')

audit: $(BUILD)/assumptions.txt
	@cat $<
	@if grep -v '^===' $< | grep -qE '($(AUDIT_NS))\.'; then \
	  echo; echo "FAIL: a theorem depends on something in this development's own"; \
	  echo "namespace, which means it was Admitted rather than proved."; exit 1; fi
	@if grep -nE '^[[:space:]]*(Admitted|Axiom|Parameter)[[:space:].]' $(SRC)/*.v; then \
	  echo; echo "FAIL: Admitted/Axiom/Parameter found in the sources above."; exit 1; fi
	@if grep -nE '(^|[^_[:alnum:]])admit[[:space:]]*\.' $(SRC)/*.v; then \
	  echo; echo "FAIL: admit found in the sources above."; exit 1; fi
	@echo
	@echo "OK: no admits, and no axioms beyond the ones VST and CompCert use."

$(BUILD)/assumptions.txt: $(BUILD)/Link.vo
	@for t in $(AUDIT_THMS); do \
	  echo "=================== $(TOP).$$t ==================="; \
	  printf 'Require %s.Verif_fib %s.Link.\nPrint Assumptions %s.%s.\n' \
	    $(TOP) $(TOP) $(TOP) $$t > $(BUILD)/_audit.v; \
	  $(COQC) $(COQFLAGS) -o $(BUILD)/_audit.vo $(BUILD)/_audit.v; \
	  echo; \
	done > $@

# --- smoke test --------------------------------------------------------

smoke: $(BUILD)/fib
	@echo "(expected values computed from the Coq model: fib n mod 2^64)"
	@set -e; \
	check() { got=$$(echo "$$1" | $(BUILD)/fib); \
	  if [ "$$got" != "$$2" ]; then echo "FAIL: fib($$1) = $$got, expected $$2"; exit 1; fi; \
	  echo "ok: fib($$1) = $$got"; }; \
	check 0 0; check 1 1; check 2 1; check 3 2; check 10 55; \
	check 50 12586269025; \
	check 93 12200160415121876738; \
	check 94 1293530146158671551; \
	check 95 13493690561280548289; \
	check 100 3736710778780434371; \
	check 200 17323038258947941269
	@echo "smoke tests passed"

clean:
	rm -rf $(BUILD) $(SRC)/fib.v $(SRC)/main.v
