# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "mptsas" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "leaf";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "leaf/nix";
      fsType = "zfs";
    };

  #fileSystems."/boot" =
  #  { device = "/dev/disk/by-uuid/REDACTED";
  #    fsType = "ext4";
  #  };

  fileSystems."/boot" =
    { device = config.gensokyo.disks.boot or "/dev/disk/by-label/MAUSOLEUM_BOOT";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  #networking.hostId = "AAAAAAAA";
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  boot.kernelParams = ["boot.shell_on_fail"];

  boot.initrd.secrets = {"/leaf.h" = "/var/secret/crypt/leaf.h";};

  boot.initrd.luks.devices = {
    crypted = {
      device = config.gensokyo.disks.crypted or "/dev/disk/by-label/mausoleum-crypted";
      header = "/leaf.h";
      preLVM = true;
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
