{
  description = "VST/CompCert template: an end-to-end verified Fibonacci program";

  # Pinned to the exact nixpkgs already present in this machine's store
  # (the `to.path` of the `nixpkgs` entry in /etc/nix/registry.json), so that
  # nothing has to be rebuilt or refetched.
  #
  # To make this flake portable to another machine, replace the line below with
  # a normal revision pin, e.g.
  #     inputs.nixpkgs.url = "github:NixOS/nixpkgs/<rev>";
  # Any nixpkgs providing coq 9.1 / VST 2.16 / CompCert 3.17 will do.
  inputs.nixpkgs.url = "path:/nix/store/ww3132d3ajq53n9xx2s8mic73jk91j4r-source";

  outputs = { self, nixpkgs }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" ];
      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f (mk system));

      mk = system:
        let
          # CompCert is distributed under the INRIA non-commercial licence,
          # which nixpkgs classifies as unfree.  Verifying C with VST is
          # impossible without it, so the template opts in explicitly.
          pkgs = import nixpkgs { inherit system; config.allowUnfree = true; };

          cp = pkgs.coqPackages;
          inherit (cp) coq VST compcert ITree;
          coqVersion = coq.coq-version;

          # VST ships a handful of ITree-dependent files as source only -- its
          # Makefile never builds them, so nixpkgs installs no .vo for them.
          # We need three: the putchar/getchar funspecs and external
          # specification (io_specs), and the juicy-to-dry erasure used by the
          # whole-program safety theorem (dry_mem_lemmas, io_dry).
          #
          # Rather than vendoring VST source into this repo, compile them here
          # into VST's own namespace, so `Require Import VST.progs64.io_specs`
          # works exactly as if upstream had built it.
          vst-io = pkgs.stdenv.mkDerivation {
            pname = "coq${coqVersion}-VST-io";
            inherit (VST) version;
            dontUnpack = true;
            strictDeps = false;
            nativeBuildInputs = [ coq compcert.lib VST ITree ];
            buildPhase = ''
              runHook preBuild
              mkdir -p VST/progs64
              src=${VST}/lib/coq/${coqVersion}/user-contrib/VST
              # io.v is the AST of VST's own io.c; io_dry.v carries an unused Require
              # for it, so build it too rather than patching upstream source.
              for f in io io_specs dry_mem_lemmas io_dry; do
                cp $src/progs64/$f.v VST/progs64/
              done
              # in dependency order
              coqc -Q VST VST VST/progs64/io.v
              coqc -Q VST VST VST/progs64/io_specs.v
              coqc -Q VST VST VST/progs64/dry_mem_lemmas.v
              coqc -Q VST VST VST/progs64/io_dry.v
              runHook postBuild
            '';
            installPhase = ''
              runHook preInstall
              d=$out/lib/coq/${coqVersion}/user-contrib/VST/progs64
              mkdir -p $d
              cp VST/progs64/*.v VST/progs64/*.vo $d/
              runHook postInstall
            '';
            meta = {
              description = "ITree-dependent VST modules that upstream ships source-only";
              inherit (VST.meta) platforms;
            };
          };

          # Only the inputs the Makefile needs; in particular not build/,
          # so that stale artifacts cannot leak into a derivation.
          projectSrc = pkgs.lib.cleanSourceWith {
            src = self;
            name = "fib-vst-src";
            filter = path: type:
              let rel = pkgs.lib.removePrefix (toString self + "/") (toString path);
              # src/fib.v and src/main.v are clightgen output: transient, and
              # regenerated by the build.
              in rel == "Makefile" || rel == "src"
                 || (pkgs.lib.hasPrefix "src/" rel
                     && rel != "src/fib.v" && rel != "src/main.v");
          };

          # Everything needed to run the Makefile.
          buildDeps = [ coq VST compcert compcert.lib ITree vst-io pkgs.gnumake ];

          fib = pkgs.stdenv.mkDerivation {
            pname = "fib";
            version = "1.0";
            src = projectSrc;
            strictDeps = false;
            nativeBuildInputs = buildDeps;
            buildPhase = ''
              runHook preBuild
              make bin
              runHook postBuild
            '';
            installPhase = ''
              runHook preInstall
              install -Dm755 build/fib $out/bin/fib
              runHook postInstall
            '';
            meta.mainProgram = "fib";
          };

          # `nix flake check`: run clightgen, compile every proof, audit the
          # axioms the end-to-end theorem actually depends on, and smoke-test
          # the compiled binary.
          proofs = pkgs.stdenv.mkDerivation {
            pname = "fib-proofs";
            version = "1.0";
            src = projectSrc;
            strictDeps = false;
            nativeBuildInputs = buildDeps;
            buildPhase = ''
              runHook preBuild
              make all
              make audit
              runHook postBuild
            '';
            doCheck = true;
            checkPhase = ''
              runHook preCheck
              make smoke
              runHook postCheck
            '';
            installPhase = ''
              runHook preInstall
              mkdir -p $out
              cp build/*.vo build/assumptions.txt $out/
              runHook postInstall
            '';
          };

          devShell = pkgs.mkShell {
            packages = buildDeps;
            shellHook = ''
              echo "VST template devshell: coq ${coqVersion}, VST ${VST.version}, CompCert ${compcert.version}"
              echo "  make        clightgen + ccomp + check every proof"
              echo "  make audit  print the axioms the end-to-end theorem rests on"
              echo "  make smoke  run the compiled program on a few inputs"
            '';
          };
        in
        { inherit vst-io fib proofs devShell; };
    in
    {
      packages = forAllSystems (o: {
        inherit (o) vst-io fib proofs;
        default = o.fib;
      });

      checks = forAllSystems (o: {
        inherit (o) proofs;
        default = o.proofs;
      });

      devShells = forAllSystems (o: { default = o.devShell; });
    };
}
