# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

    #boot.kernelParams = ["console=tty0" "console=ttyUSB0" "earlyprintk=serial,ttyUSB0" "rootdelay=10"];
    boot.kernelParams = [];
    boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
    boot.initrd.kernelModules = [
      # for mounting ESP partition
      "vfat"
      "nls_utf8"
      "nls_iso8859_1"
      "nls_cp437"
      "nls_iso8859_1"

      # usb serial devices
      # "usbcore"
      # "usbserial"
      # "ftdi_sio"      # FTDI USB-serial chips (very common)
      # "cp210x"        # Silicon Labs CP210x chips
      # "ch341"         # WinChipHead CH341 chips  
      # "pl2303"        # Prolific PL2303 chips
      # "cdc_acm"       # USB CDC ACM (modem) devices
    ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    boot.loader.systemd-boot.enable = lib.mkForce false;

    boot.lanzaboote = {
      enable = true;
      pkiBundle = "/var/secret/secureboot";
    };

    #systemd.services."serial-getty@ttyUSB0".enable = true;

    boot.supportedFilesystems = [ "vfat" ];
    boot.zfs.requestEncryptionCredentials = false;

    boot.initrd.luks.devices = {
      fern0 = {
        device = config.gensokyo.disks.fern0 or "/dev/disk/by-label/furnace-fern0";
        header = "/boot/crypt/fern0.h";
      };
      fern1 = {
        device = config.gensokyo.disks.fern1 or "/dev/disk/by-label/furnace-fern1";
        header = "/boot/crypt/fern1.h";
      };
    };

    boot.initrd.systemd.services.mount-boot = {
      description = "Mount /boot for LUKS headers";
      before = [
        "systemd-cryptsetup@fern0.service"
        "systemd-cryptsetup@fern1.service"
      ];
      requiredBy = [
        "systemd-cryptsetup@fern0.service"
        "systemd-cryptsetup@fern1.service"
      ];
      unitConfig = {
        DefaultDependencies = false;
      };
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStartPre = "${pkgs.coreutils}/bin/mkdir -p /boot";
        ExecStart = "${pkgs.util-linux}/bin/mount -t vfat ${config.gensokyo.disks.boot or "/dev/disk/by-label/FURNACE_BOOT"} /boot";
        #ExecStop = "${pkgs.util-linux}/bin/umount /boot";
      };
    };

    boot.initrd.systemd.storePaths = [ "${pkgs.util-linux}/bin/mount" "${pkgs.util-linux}/bin/umount" "${pkgs.coreutils}/bin/mkdir" ];

    fileSystems."/" = {
      device = "fern";
      fsType = "zfs";
    };

    fileSystems."/boot" = {
      device = config.gensokyo.disks.boot or "/dev/disk/by-label/FURNACE_BOOT";
      fsType = "vfat";
      neededForBoot = true;
      options = [ "fmask=0022" "dmask=0022" ];
    };

    fileSystems."/home" = {
      device = "fern/home";
      fsType = "zfs";
    };

    fileSystems."/nix" = {
      device = "fern/nix";
      fsType = "zfs";
    };

    fileSystems."/srv" = {
      device = "fern/srv";
      fsType = "zfs";
    };

    fileSystems."/srv/jellyfin" = {
      device = "fern/srv/jellyfin";
      fsType = "zfs";
    };

    fileSystems."/srv/komga" = {
      device = "fern/srv/komga";
      fsType = "zfs";
    };

    fileSystems."/srv/webdav" = {
      device = "fern/srv/webdav";
      fsType = "zfs";
    };

    fileSystems."/srv/nextcloud" = {
      device = "fern/srv/nextcloud";
      fsType = "zfs";
    };

    fileSystems."/srv/torrent" = {
      device = "fern/srv/torrent";
      fsType = "zfs";
    };

    fileSystems."/srv/log" = {
      device = "fern/srv/log";
      fsType = "zfs";
    };

    environment.etc.crypttab = {
      mode = "0600";
      text = ''
        # <volume-name> <encrypted-device> [key-file] [options]
        yet0 ${config.gensokyo.disks.yet0 or "/dev/disk/by-label/furnace-yet0"} /var/secret/yet/yet0.k header=/var/secret/yet/yet0.h
        yet1 ${config.gensokyo.disks.yet1 or "/dev/disk/by-label/furnace-yet1"} /var/secret/yet/yet1.k header=/var/secret/yet/yet1.h
      '';
    };

    fileSystems."/yet" = {
      device = "yet";
      fsType = "zfs";
      options = [ "nofail" ];
      #depends = [ "/dev/mapper/yet0" "/dev/mapper/yet1" ];
    };

    #systemd.services."zfs-import-yet".after = lib.mkForce [ "decrypt-yet.service" ];

    swapDevices = [ ];
    networking.useDHCP = lib.mkDefault true;
    #networking.hostId = "AAAAAAAA";

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
